export const SET_CONTROL_POINT = "SET_CONTROL_POINT";
export const SET_CONTROL_POINT_AXIS = "SET_CONTROL_POINT_AXIS";

export const ADD_PROP_CSS = "ADD_PROP_CSS";
export const EDIT_PROP_CSS = "EDIT_PROP_CSS";
export const SET_PROP_CSS_VALUE = "EDIT_PROP_CSS_VALUE";
export const REMOVE_PROP_CSS = "REMOVE_PROP_CSS";
export const TRANSFORM_PROP_CSS = "TRANSFORM_PROP_CSS";

export const SET_FRAME = "SET_FRAME";
export const SET_ANIMATION_FRAME = "SET_ANIMATION_FRAME";
export const ADD_ANIMATION_FRAME = "ADD_ANIMATION_FRAME";
export const REMOVE_ANIMATION_FRAME = "REMOVE_ANIMATION_FRAME";

export const ADD_ANIMATION = "ADD_ANIMATION";
export const DELETE_ANIMATION = "DELETE_ANIMATION";
export const SET_ANIMATION = "SET_ANIMATION";
export const CHANGE_ANIMATION = "CHANGE_ANIMATION";
export const SET_ANIMATION_PARAMETER = "SET_ANIMATION_PARAMETER";
export const SET_ANIMATION_FRAME_TIMING = "SET_ANIMATION_FRAME_TIMING";
